<pre>--- Summary ---
Tests passed: 0 out of 4

--- Details ---
Test #0: failed 
Test case description: ML4T-220
Traceback:
  File "grade_strategy_learner.py", line 443, in test_strategy
    raise IncorrectOutput(
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'symbol': 'ML4T-220', 'sd': datetime.datetime(2008, 1, 1, 0, 0), 'ed': datetime.datetime(2009, 12, 31, 0, 0), 'sv': 100000}
    outsample_args: {'symbol': 'ML4T-220', 'sd': datetime.datetime(2010, 1, 1, 0, 0), 'ed': datetime.datetime(2011, 12, 31, 0, 0), 'sv': 100000}
    benchmark_type: clean
    benchmark: 1.0
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-0.0025747799999999987) did not beat benchmark (1.0)
  out-sample return (0.06083202000000054) did not beat benchmark (1.0)

Test #1: failed 
Test case description: AAPL
Traceback:
  File "grade_strategy_learner.py", line 443, in test_strategy
    raise IncorrectOutput(
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'symbol': 'AAPL', 'sd': datetime.datetime(2008, 1, 1, 0, 0), 'ed': datetime.datetime(2009, 12, 31, 0, 0), 'sv': 100000}
    outsample_args: {'symbol': 'AAPL', 'sd': datetime.datetime(2010, 1, 1, 0, 0), 'ed': datetime.datetime(2011, 12, 31, 0, 0), 'sv': 100000}
    benchmark_type: stock
    benchmark: 0.1581999999999999
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (0.07099999999999995) did not beat benchmark (0.1581999999999999)

Test #2: failed 
Test case description: SINE_FAST_NOISE
Traceback:
  File "grade_strategy_learner.py", line 443, in test_strategy
    raise IncorrectOutput(
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'symbol': 'SINE_FAST_NOISE', 'sd': datetime.datetime(2008, 1, 1, 0, 0), 'ed': datetime.datetime(2009, 12, 31, 0, 0), 'sv': 100000}
    outsample_args: {'symbol': 'SINE_FAST_NOISE', 'sd': datetime.datetime(2010, 1, 1, 0, 0), 'ed': datetime.datetime(2011, 12, 31, 0, 0), 'sv': 100000}
    benchmark_type: noisy
    benchmark: 2.0
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-0.14334743698899988) did not beat benchmark (2.0)

Test #3: failed 
Test case description: UNH - In sample
Traceback:
  File "grade_strategy_learner.py", line 443, in test_strategy
    raise IncorrectOutput(
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'symbol': 'UNH', 'sd': datetime.datetime(2008, 1, 1, 0, 0), 'ed': datetime.datetime(2009, 12, 31, 0, 0), 'sv': 100000}
    outsample_args: {'symbol': 'UNH', 'sd': datetime.datetime(2010, 1, 1, 0, 0), 'ed': datetime.datetime(2011, 12, 31, 0, 0), 'sv': 100000}
    benchmark_type: stock
    benchmark: -0.25239999999999996
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-0.28779999999999994) did not beat benchmark (-0.25239999999999996)

</pre>
